### ISSUE TITLE
on suggestion some picture appeared, some didn't.

### ISSUE THREAD

**Issue by jampttws** [darmonlyone/WholeFoodBook#29]
![screen shot 2561-11-14 at 11 11 26 pm](https://user-images.githubusercontent.com/32285946/48495632-08180b80-e863-11e8-893c-2ba736068fae.png)

**Comment by jampttws** [comment]
![screen shot 2561-11-14 at 11 20 14 pm](https://user-images.githubusercontent.com/32285946/48496121-e23f3680-e863-11e8-905f-5603d626cbdb.png)

**Comment by darmonlyone** [comment]
We already have fix some of this problem on ISSUE #24 .
