### ISSUE TITLE
Page crashed when clicked 'Continue' button

### ISSUE THREAD

**Issue by neung123** [darmonlyone/WholeFoodBook#35]
I'm not sure about your app design but in /login when I click 'Continue' button the page crashed, in cmd it returned `AttributeError: 'NoneType' object has no attribute 'split'` and then I can't clicked ' login with facebook' button or 'login with google' button, I had to refreshed the page before clicked login button.

**Comment by darmonlyone** [comment]
It's usually working normally, to avoid one of this `error` you should waiting all component on those page loading fish before clicking anything.
