### ISSUE TITLE
'Filter By' button and 'Clear Filter' button doesn't work.

### ISSUE THREAD

**Issue by NokKbl** [darmonlyone/WholeFoodBook#44]
Don't have any response from 'Filter By' button and 'Clear Filter' button when click. It doesn't work as it should.

<img src="http://drive.google.com/uc?export=view&id=1RfAJQn5L9eQkHfHVZKFdLnJJLLMF5kAl">

**Comment by darmonlyone** [comment]
This issue can fixed on #51
