### ISSUE TITLE
Picture doesn't show in Carrot Soup with Yogurt page.

### ISSUE THREAD

**Issue by KorawitRupanya** [darmonlyone/WholeFoodBook#46]

**Comment by KorawitRupanya** [comment]
[https://whole-food-cookbook.herokuapp.com/recipe/Carrot%20Soup%20with%20Yogurt](url)

**Comment by darmonlyone** [comment]
Its usually working normally for me, maybe you internet was slow so you browser can't access those image.
![image](https://user-images.githubusercontent.com/32285746/49465155-6cf5ce80-f82f-11e8-830f-7c560bc52a0e.png)
