### ISSUE TITLE
Appetiser menu have some dessert menu.

### ISSUE THREAD

**Issue by KorawitRupanya** [darmonlyone/WholeFoodBook#49]
By the diffinition of appetiser which is a small amount of food eaten before a meal then some menu shouldn't have in both appetiser and dessert. ref[https://dictionary.cambridge.org/dictionary/english/appetizer](url)

**Comment by darmonlyone** [comment]
This kind of issue is occur on recipe owner. Maybe recipe owner mark it uncollected during add new recipe.
